sudo: required

language: node_js

node_js: node

cache: yarn

install:
  - wget https://yarnpkg.com/latest.tar.gz && tar -xf latest.tar.gz && dist/bin/yarn

script:
  - cd ./server && yarn install && yarn test
