sudo: required

language: node_js

node_js: node

cache: yarn

install:
  - npm install -g yarn && yarn

script:
  - cd ./server && yarn install && yarn test
  - cd ../client && yarn install && yarn test
